# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:          Bobbing for Kernels
email:          kbob@jogger-egg.com
description:    A web-log devoted to the geekly arts.
url:            "http://kbob.github.io"

# Centrarium settings
subtitle:       ""
name:           Bob Miller
cover:          /images/foggy-strip.jpg
# logo:         ""
inter_post_navigation: true

# Custom
paginate: 10

# Archive (Centrarium (see https://github.com/jekyll/jekyll-archives/)
# Not using archives -- github.io does not support.
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layout: 'archive'
#   permalinks:
#     category: '/category/:name/'
#     tag: '/tag/:name/'

# Social (Centrarium)
social:
  - name: GitHub
    icon: github
    username: kbob
    url: https://github.com/kbob
    desc: Fork me on GitHub
    share: false

  - name: Reddit
    icon: reddit
    username: u/kbob
    url: https://reddit.com/u/kbob
    desc: Share to Reddit
    share: true

  - name: Mastodon
    icon: mastodon
    username: "@kbob@chaos.social"
    url: https://chaos.social/@kbob
    desc: Toot with me on Mastodon
    share: false

# Protocols (Centrarium)
protocols:
  os_repo: "https://github.com/kbob/kbob.github.io"
  os_rcs_type: git
  os_src: "https://github.com/kbob/kbob.github.io.git"

# --- Following are Jekyll defaults as comments plus my changes.
#     https://jekyllrb.com/docs/configuration/#default-configuration

## Where things are
# source:       .
# destination:  ./_site
# plugins_dir:  ./_plugins
# layouts_dir:  ./_layouts
# data_dir:     ./_data
# includes_dir: ./_includes
# collections:  null

## Handling Reading
# safe:         false
# include:      [".htaccess"]
# exclude:      []
exclude:      [README.md]
# keep_files:   [".git", ".svn"]
# encoding:     "utf-8"
# markdown_ext: "markdown,mkdown,mkdn,mkd,md"

## Filtering Content
# show_drafts: null
# limit_posts: 0
# future:      false
# unpublished: false

## Plugins
# whitelist: []
# gems:      []
plugins:      [jekyll-paginate]

## Conversion
# markdown:    kramdown
# highlighter: rouge
# lsi:         false
# excerpt_separator: "\n\n"
# incremental: false

## Serving
# detach:  false
# port:    4000
# host:    127.0.0.1
# baseurl: "" # does not include hostname

## Outputting
# permalink:     date
permalink: /:year/:month/:day/:title
# paginate_path: /page:num
timezone: America/Los_Angeles

# quiet:    false
# defaults: []
defaults:
 - 
   scope:
     path: ""
   values:
     author: "kbob"

## Markdown Processors
# rdiscount:
#   extensions: []

# redcarpet:
#   extensions: []

# kramdown:
#   auto_ids:       true
#   footnote_nr:    1
#   entity_output:  as_char
#   toc_levels:     1..6
#   smart_quotes:   lsquo,rsquo,ldquo,rdquo
#   enable_coderay: false

#   coderay:
#     coderay_wrap:              div
#     coderay_line_numbers:      inline
#     coderay_line_number_start: 1
#     coderay_tab_width:         4
#     coderay_bold_every:        10
#     coderay_css:               style
